# Generated by Django 3.1.5 on 2021-02-13 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210212_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, max_length=254, upload_to=None),
            preserve_default=False,
        ),
    ]
