# Generated by Django 3.1.5 on 2021-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
