# Generated by Django 3.1.5 on 2021-02-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210214_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
