# Generated by Django 3.1.5 on 2021-02-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='home/static/avatar/default/profile.jpg', upload_to='accounts/static/avatar'),
        ),
    ]
