# Generated by Django 3.1.5 on 2021-02-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210217_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='home/static/avatar/profile.jpg', upload_to='accounts/static/avatar'),
        ),
    ]
