# Generated by Django 3.1.5 on 2021-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210217_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='home/static/avatar/profile.jpg', upload_to='home/static/avatar'),
        ),
    ]
