# Generated by Django 3.1.5 on 2021-02-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210217_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/profile.jpg', upload_to='avatar'),
        ),
    ]
