# Generated by Django 3.1.5 on 2021-02-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210217_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='https://raw.githubusercontent.com/OlgaKoplik/CodePen/master/profile.jpg', upload_to='home/static/gallery'),
        ),
    ]
