# Generated by Django 3.1.5 on 2021-02-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210217_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='home/static/gallery'),
        ),
    ]
